name: keystore_generator
description: A utility that creates a keystore and modifies build.gradle. It accepts login and password as arguments.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
